# Generated by Django 4.0.2 on 2022-02-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, default='2022-02-10', null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default='2022-02-10 20:47:43', verbose_name='Last login'),
        ),
    ]
