# Generated by Django 4.0.2 on 2022-02-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_bio_alter_profile_insta_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default='2022-02-25 17:30:32', verbose_name='Last login'),
        ),
    ]
