version: "3"

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      # POSTGRES_USER: 'postgres'
      # POSTGRES_PASSWORD: 'postgres_pw'
      # POSTGRES_DB: 'curave_db'
    # ports:
    #   - 5433:5432

  backend:
    build: ./backend
      # context: ./backend
      # args:
      #   DJANGO_ALLOWED_HOSTS: "*"
      #   DJANGO_SECRET_KEY: "*"
      #   DJANGO_CORS_ORIGIN_WHITELIST: "*"
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    # expose:
    #   - 8000
    # env_file:
    #   - ./backend/.env.dev
    depends_on:
      - db

  frontend:
    build: ./frontend
      # context: ./frontend
    # command: [ "yarn", "start" ]
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      # - ./frontend/node_modules/:/frontend/node_modules
    # environment:
    #   - CI=true
    #   - CHOKIDAR_USEPOLLING=true
    #   - REACT_APP_BACKEND_URL=http://localhost:8000
    # tty: true

volumes:
  postgres_data_dev: null